services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: app.dev
    volumes:
      - .:/go/src/wallet-service
    working_dir: /go/src/wallet-service
    command: go run main.go
    ports:
      - "3000:3000" # http
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    image: my-mysql:1.0
    container_name: database.dev
    hostname: database.dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: WAAS
    volumes:
      #- ../../_local_mysql_data:/var/lib/mysql
      #- ./shopee.sql:/tmp/shopee.sql
      #- ./import.sh:/tmp/import.sh
      - waas-data:/var/lib/mysql

volumes:
  waas-data: