basePath: /
consumes:
    - application/json
    - application/xml
definitions:
    CrateTransactionFlyway:
        properties:
            amount:
                format: int64
                type: integer
                x-go-name: Amount
            email:
                type: string
                x-go-name: Email
            idTransaction:
                format: int64
                type: integer
                x-go-name: IdTransaction
            pspName:
                format: int64
                type: integer
                x-go-name: PspName
        type: object
        x-go-package: crm-app-go/dto/input
    RegisterLeadFlywayRequestBody:
        properties:
            additionalInfo1:
                type: string
                x-go-name: AdditionalInfo1
            additionalInfo2:
                type: string
                x-go-name: AdditionalInfo2
            additionalInfo3:
                type: string
                x-go-name: AdditionalInfo3
            bussinesUnitId:
                format: int64
                type: integer
                x-go-name: BussinesUnitId
            campaignId:
                type: string
                x-go-name: CampaignId
            country_iso:
                type: string
                x-go-name: Country_iso
            email:
                type: string
                x-go-name: Email
            last_name:
                type: string
                x-go-name: Last_name
            name:
                type: string
                x-go-name: Name
            password:
                type: string
                x-go-name: Password
            phone_number:
                type: string
                x-go-name: Phone_number
            subAffiliate:
                type: string
                x-go-name: SubAffiliate
            tag:
                type: string
                x-go-name: Tag
            tag1:
                type: string
                x-go-name: Tag1
        type: object
        x-go-package: crm-app-go/dto/input
    RegisterTransactionSuccessModel:
        properties:
            payload:
                properties:
                    message:
                        type: string
                        x-go-name: Message
                        x-order: "0"
                type: object
                x-go-name: Payload
        type: object
        x-go-package: crm-app-go/dto/output
    RegisterUserSuccessModel:
        properties:
            payload:
                properties:
                    accountId:
                        type: string
                        x-go-name: AccountId
                        x-order: "1"
                    url:
                        type: string
                        x-go-name: Url
                        x-order: "0"
                type: object
                x-go-name: Payload
        type: object
        x-go-package: crm-app-go/dto/output
host: localhost:3002
info:
    contact:
        email: roberto.espiritu@platimex.com.mx
        name: Roberto Espiritu
    license:
        name: MIT
        url: http://opensource.org/licenses/MIT
    termsOfService: there are no TOS at this moment, use at your own risk we take no responsibility
    title: CRM API.
    version: 0.0.1
paths:
    /api/v1/flyway/register-transactions:
        post:
            description: Register new user in crm flyway
            operationId: postRegisterTransacgtions
            parameters:
                - description: Register new transaction in crmn flyway
                  in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/CrateTransactionFlyway'
            responses:
                "200":
                    $ref: '#/responses/registerTransactionResponseStatus200'
                "400":
                    $ref: '#/responses/error400'
                "404":
                    $ref: '#/responses/error404'
                "500":
                    $ref: '#/responses/error500'
            tags:
                - Flyway
    /api/v1/flyway/register-user:
        post:
            description: Register new user in crm flyway
            operationId: postRegisterLead
            parameters:
                - description: Register new lead body request.
                  in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/RegisterLeadFlywayRequestBody'
            responses:
                "200":
                    $ref: '#/responses/registerLeadResponseStatus200'
                "400":
                    $ref: '#/responses/error400'
                "404":
                    $ref: '#/responses/error404'
                "500":
                    $ref: '#/responses/error500'
            tags:
                - Flyway
produces:
    - application/json
    - application/xml
responses:
    error400:
        description: Bad Request error Response | Validation error message or invalid json
        headers:
            code:
                format: int64
                type: integer
            message:
                type: string
    error404:
        description: Not Found error Response | Page not found or record not found
        headers:
            code:
                format: int64
                type: integer
            message:
                type: string
            payload: {}
        schema:
            properties:
                error:
                    items:
                        type: string
                    type: array
                    x-go-name: Error
            type: object
    error500:
        description: Internal server error Response | server is down or db constraint errors
        headers:
            code:
                format: int64
                type: integer
            message:
                type: string
            payload: {}
        schema:
            properties:
                error:
                    items:
                        type: string
                    type: array
                    x-go-name: Error
            type: object
    registerLeadResponseStatus200:
        description: Flyway Response With Status Code 200
        schema:
            $ref: '#/definitions/RegisterUserSuccessModel'
    registerTransactionResponseStatus200:
        description: Flyway Response With Status Code 200
        schema:
            $ref: '#/definitions/RegisterTransactionSuccessModel'
schemes:
    - http
    - https
swagger: "2.0"
x-meta-array:
    - value1
    - value2
x-meta-array-obj:
    - name: obj
      value: field
x-meta-value: value
